version: '3.7'
services:
  django:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
  angular:
    build:  
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "4200:4200"