# Generated by Django 3.2.25 on 2024-05-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='', max_length=70)),
                ('startTime', models.CharField(default='', max_length=70)),
                ('is_free_time', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('worker_restrictions', models.ManyToManyField(to='schedulerASP.Turn')),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('space_capacity', models.IntegerField(default=0)),
                ('space_restrictions', models.ManyToManyField(to='schedulerASP.Turn')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduableTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('task_size', models.IntegerField(default=0)),
                ('task_restrictions', models.ManyToManyField(blank=True, null=True, to='schedulerASP.Turn')),
                ('task_spaces', models.ManyToManyField(blank=True, null=True, to='schedulerASP.Space')),
                ('task_tags', models.ManyToManyField(blank=True, null=True, to='schedulerASP.Tag')),
                ('task_workers', models.ManyToManyField(blank=True, null=True, to='schedulerASP.Worker')),
            ],
        ),
    ]
