# Generated by Django 4.2.13 on 2024-06-12 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('turnsDuration', models.IntegerField(default=0)),
                ('turnsPerDay', models.IntegerField(default=0)),
                ('start_time', models.CharField(default='', max_length=70)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='', max_length=70)),
                ('startTime', models.CharField(default='', max_length=70)),
                ('is_free_time', models.BooleanField(default=False)),
                ('timeTable_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='schedulerASP.timetable')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('restrictionsWorker', models.ManyToManyField(blank=True, null=True, related_name='workers', to='schedulerASP.turn')),
                ('timeTable_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='schedulerASP.timetable')),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('space_capacity', models.IntegerField(blank=True, default=0, null=True)),
                ('restrictionsSpace', models.ManyToManyField(blank=True, null=True, related_name='spaces', to='schedulerASP.turn')),
                ('timeTable_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='schedulerASP.timetable')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('day', models.CharField(default='', max_length=70)),
                ('number', models.IntegerField(default=0)),
                ('schedule_space', models.CharField(default='', max_length=70)),
                ('schedule_worker', models.CharField(default='', max_length=70)),
                ('timeTable_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeTable_schedule', to='schedulerASP.timetable')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduableTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('task_size', models.IntegerField(blank=True, default=0, null=True)),
                ('task_tags', models.JSONField(blank=True, default=list, null=True)),
                ('task_restrictions', models.ManyToManyField(blank=True, null=True, related_name='task_restrictions', to='schedulerASP.turn')),
                ('task_spaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduable_tasks', to='schedulerASP.space')),
                ('task_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduable_tasks', to='schedulerASP.worker')),
                ('timeTable_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduable_tasks', to='schedulerASP.timetable')),
            ],
        ),
        migrations.CreateModel(
            name='CommonWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommonSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('space_capacity', models.IntegerField(blank=True, default=0, null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommonScheduableTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('task_size', models.IntegerField(blank=True, default=0, null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduable_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
