# Generated by Django 3.2.25 on 2024-05-14 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerASP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='worker_restrictions',
        ),
        migrations.CreateModel(
            name='WorkerTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulerASP.turn')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulerASP.worker')),
            ],
        ),
    ]
