# Generated by Django 3.2.25 on 2024-05-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerASP', '0002_auto_20240514_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turn',
            old_name='startTime',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='worker',
            name='worker_restrictions',
            field=models.ManyToManyField(related_name='workers', to='schedulerASP.Turn'),
        ),
    ]
