# Generated by Django 3.2.25 on 2024-05-14 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerASP', '0003_auto_20240514_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turn',
            old_name='start_time',
            new_name='startTime',
        ),
    ]
