# Generated by Django 3.2.25 on 2024-05-14 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerASP', '0004_rename_start_time_turn_starttime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='worker_restrictions',
            new_name='restrictionsWorker',
        ),
    ]
