# Generated by Django 3.2.25 on 2024-05-22 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerASP', '0005_rename_worker_restrictions_worker_restrictionsworker'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('turnsDuration', models.IntegerField(default=0)),
                ('turnsPerDay', models.IntegerField(default=0)),
                ('unavailableDay', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='scheduabletask',
            name='task_workers',
        ),
        migrations.RemoveField(
            model_name='space',
            name='space_restrictions',
        ),
        migrations.AddField(
            model_name='scheduabletask',
            name='task_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduable_tasks', to='schedulerASP.worker'),
        ),
        migrations.AddField(
            model_name='space',
            name='restrictionsSpace',
            field=models.ManyToManyField(related_name='spaces', to='schedulerASP.Turn'),
        ),
        migrations.AlterField(
            model_name='scheduabletask',
            name='task_restrictions',
            field=models.ManyToManyField(blank=True, related_name='task_restrictions', to='schedulerASP.Turn'),
        ),
        migrations.RemoveField(
            model_name='scheduabletask',
            name='task_spaces',
        ),
        migrations.AddField(
            model_name='scheduabletask',
            name='task_spaces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduable_tasks', to='schedulerASP.space'),
        ),
        migrations.AlterField(
            model_name='scheduabletask',
            name='task_tags',
            field=models.ManyToManyField(blank=True, related_name='task_tags', to='schedulerASP.Tag'),
        ),
        migrations.DeleteModel(
            name='WorkerTurn',
        ),
    ]
