# Generated by Django 3.2.25 on 2024-05-22 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerASP', '0006_auto_20240522_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('day', models.CharField(default='', max_length=70)),
                ('number', models.IntegerField(default=0)),
                ('schedule_space', models.CharField(default='', max_length=70)),
                ('schedule_worker', models.CharField(default='', max_length=70)),
                ('timeTable_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeTable_schedule', to='schedulerASP.timetable')),
            ],
        ),
    ]
