# Generated by Django 3.2.25 on 2024-05-22 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerASP', '0007_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='unavailableDay',
        ),
    ]
