# Generated by Django 3.2.25 on 2024-05-23 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerASP', '0008_remove_timetable_unavailableday'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='timeTable_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='schedulerASP.timetable'),
            preserve_default=False,
        ),
    ]
