# Generated by Django 3.2.25 on 2024-05-23 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerASP', '0009_turn_timetable_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('password', models.CharField(default='', max_length=70)),
                ('email', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='space',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='schedulerASP.user'),
        ),
    ]
