# Generated by Django 3.2.25 on 2024-05-24 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerASP', '0010_auto_20240523_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='user_id',
        ),
        migrations.AddField(
            model_name='space',
            name='timeTable_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='schedulerASP.timetable'),
        ),
        migrations.CreateModel(
            name='CommonSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('space_capacity', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='schedulerASP.user')),
            ],
        ),
    ]
