# Generated by Django 3.2.25 on 2024-05-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerASP', '0011_auto_20240524_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='restrictionsSpace',
            field=models.ManyToManyField(blank=True, related_name='spaces', to='schedulerASP.Turn'),
        ),
        migrations.AlterField(
            model_name='space',
            name='space_capacity',
            field=models.IntegerField(blank=True),
        ),
    ]
