# Generated by Django 3.2.25 on 2024-05-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerASP', '0012_auto_20240526_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='space_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
