# Generated by Django 3.2.25 on 2024-05-26 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerASP', '0013_alter_space_space_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='timtable_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='schedulerASP.timetable'),
        ),
        migrations.AlterField(
            model_name='space',
            name='restrictionsSpace',
            field=models.ManyToManyField(related_name='spaces', to='schedulerASP.Turn'),
        ),
        migrations.AlterField(
            model_name='space',
            name='space_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CommonWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='schedulerASP.user')),
            ],
        ),
    ]
