# Generated by Django 3.2.25 on 2024-05-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerASP', '0014_auto_20240526_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='restrictionsSpace',
            field=models.ManyToManyField(blank=True, related_name='spaces', to='schedulerASP.Turn'),
        ),
    ]
