# Generated by Django 3.2.25 on 2024-05-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerASP', '0015_alter_space_restrictionsspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='restrictionsSpace',
            field=models.ManyToManyField(blank=True, null=True, related_name='spaces', to='schedulerASP.Turn'),
        ),
        migrations.AlterField(
            model_name='space',
            name='space_capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
