# Generated by Django 3.2.25 on 2024-05-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerASP', '0016_auto_20240526_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonspace',
            name='space_capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
