# Generated by Django 3.2.25 on 2024-05-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerASP', '0017_alter_commonspace_space_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='restrictionsWorker',
            field=models.ManyToManyField(blank=True, null=True, related_name='workers', to='schedulerASP.Turn'),
        ),
    ]
