# Generated by Django 3.2.25 on 2024-05-27 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerASP', '0018_alter_worker_restrictionsworker'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduabletask',
            name='timeTable_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduable_tasks', to='schedulerASP.timetable'),
        ),
        migrations.AlterField(
            model_name='scheduabletask',
            name='task_restrictions',
            field=models.ManyToManyField(blank=True, null=True, related_name='task_restrictions', to='schedulerASP.Turn'),
        ),
        migrations.AlterField(
            model_name='scheduabletask',
            name='task_size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scheduabletask',
            name='task_tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='task_tags', to='schedulerASP.Tag'),
        ),
    ]
