# Generated by Django 3.2.25 on 2024-05-27 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerASP', '0019_auto_20240527_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonScheduableTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduable_tasks', to='schedulerASP.user')),
            ],
        ),
    ]
