# Generated by Django 3.2.25 on 2024-05-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerASP', '0020_commonscheduabletask'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonscheduabletask',
            name='task_size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
