# Generated by Django 3.2.25 on 2024-05-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerASP', '0021_commonscheduabletask_task_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduabletask',
            name='task_tags',
        ),
        migrations.AddField(
            model_name='scheduabletask',
            name='task_tags',
            field=models.JSONField(default=list),
        ),
    ]
