# Generated by Django 3.2.25 on 2024-06-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerASP', '0022_auto_20240527_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='start_time',
            field=models.CharField(default='', max_length=70),
        ),
    ]
