# Generated by Django 3.2.25 on 2024-06-03 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerASP', '0023_timetable_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='schedulerASP.user'),
        ),
    ]
